version: '3.6'
services:
  http:
    image: nginx:1.17.9
    container_name: http.apatris-ref.prod
    ports:
      - '81:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../backend/doc:/docs
      - ../../backend/schema.graphql:/docs/api/schema.graphql
    links:
      - backend:backend.apatris-ref.prod
    depends_on:
      - backend

  postgres:
    image: postgres:12.2
    container_name: postgres.apatris-ref.prod
    env_file:
      - ./config.env
    volumes:
      - ../../data/postgres/local:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:5.0.8
    container_name: redis.apatris-ref.prod
    entrypoint: ['redis-server', '/usr/local/etc/redis/default.conf']
    volumes:
      - ./redis.conf:/usr/local/etc/redis/default.conf
      - ../../data/redis/local:/data

  backend:
    image: backend.apatris-ref.prod
    container_name: backend.apatris-ref.prod
    env_file:
      - ./config.env
    links:
      - postgres:postgres.apatris-ref.prod
      - redis:redis.apatris-ref.prod
    volumes:
      - ../../backend:/app
      - ../../data/roi.csv:/app/roi.csv
    depends_on:
      - postgres
      - redis

  mail:
    image: schickling/mailcatcher
    container_name: mail.apatris-ref.prod
    ports:
      - '1080:1080'