AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*.rb'
    - 'spec/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 80

Metrics/ClassLength:
  Max: 200
