# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1', '>= 6.1.3.1'
# Use pg as the database for Active Record
gem 'pg', '~> 1.2', '>= 1.2.3'
# Use Puma as the app server
gem 'puma', '~> 5.2', '>= 5.2.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.2', '>= 4.2.5'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.7', '>= 1.7.3', require: false

gem 'activeadmin', '~> 2.9'
gem 'devise', '~> 4.7', '>= 4.7.3'
gem 'execjs', '~> 2.7'
gem 'sass-rails', '~> 6.0'
gem 'therubyracer', '~> 0.12.3'
gem 'uglifier', '~> 4.2'

gem 'sidekiq', '~> 6.2', '>= 6.2.1'
gem 'sidekiq-scheduler', '~> 3.0', '>= 3.0.1'
gem 'rubocop', '~> 1.12', '>= 1.12.1'
gem 'rest-client', '~> 2.1'

gem 'eth', '~> 0.4.12'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot_rails', '~> 4.10'
  gem 'json-schema'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'rspec_api_documentation'

  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'guard-migrate'
  gem 'guard-shell'
  gem 'spring-commands-rspec'
end

group :development do
  gem 'annotate', '~> 3.1', '>= 3.1.1'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rails-erd', '~> 1.6', '>= 1.6.1'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

